# Generated by Django 5.1.6 on 2025-02-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
