# Generated by Django 5.1.6 on 2025-02-25 20:32

import user_account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0011_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["date_joined"],
                "verbose_name": "User Account",
                "verbose_name_plural": "User Accounts",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user_account.models.UserManager()),
            ],
        ),
    ]
