# Generated by Django 5.1.6 on 2025-02-23 13:01

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hired_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="mobile_number",
            field=models.CharField(
                max_length=20, validators=[employee.models.MobileNumberValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("application_received", "Application Received"),
                    ("interview scheduled", "Interview Scheduled"),
                    ("hired", "Hired"),
                    ("not accepted", "Not Accepted"),
                ],
                db_index=True,
                default="application_received",
                max_length=24,
            ),
        ),
    ]
