# Generated by Django 5.1.6 on 2025-02-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_alter_employee_email_alter_employee_hired_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("application_received", "Application Received"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("hired", "Hired"),
                    ("not_accepted", "Not Accepted"),
                ],
                db_index=True,
                default="application_received",
                max_length=24,
            ),
        ),
    ]
